version: '3.7'

services:

  backend:
      image: backend-example
      ports:
        - 127.0.0.1:8080:8080
      environment:
        - REQUEST_ORIGIN=http://localhost:5000 

  frontend:
      image: frontend-example
      ports: 
        - 127.0.0.1:5000:5000
      environment:
        - REACT_APP_BACKEND_URL=http://localhost:8080
