version: '3.7'

services:

  backend:
      image: backend-example
      ports:
        - 127.0.0.1:8080:8080
      environment:
        - REDIS_HOST=redis
        - REQUEST_ORIGIN=http://localhost:5000 
        - POSTGRES_HOST=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DATABASE=postgres
      depends_on:
        - redis
        - postgres

  frontend:
      image: frontend-example
      ports: 
        - 127.0.0.1:5000:5000
      environment:
        - REACT_APP_BACKEND_URL=http://localhost:8080

  redis:
      image: redis

  postgres:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=postgres
